###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8080
spring.application.name: websocket-server

logging.level:
  root: INFO
  org.springframework.web: INFO
  org.springframework.web.HttpLogging: INFO
  com.example.websocket: DEBUG

spring.redis:
  host: localhost   # Redis Server Host
  port: 6379        # Redis Server Port
  ssl: false        # Enable SSL support
  database: 0       # database index