###############################################################################################
# Server Configuration
###############################################################################################

server.port: 18080
spring.application.name: backend-service

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.info.enabled: true

spring:
  redis:
    host: localhost   # Redis Server Host
    port: 6379        # Redis Server Port
    ssl: false        # Enable SSL support
    database: 0       # database index